apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-front
  namespace: form-k8s-{{ .Values.global.env }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Values.global.env}}(.*)
        pathType: Prefix
        backend:
          service:
            name: front-training-app
            port:
              number: 80
      - path: /{{ .Values.global.env}}/api/(.*)
        pathType: Prefix
        backend:
          service:
            name: back-training-app
            port:
              number: 80
