apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-front
  namespace: form-k8s-acc
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /acc(.*)
        pathType: Prefix
        backend:
          service: 
            name: front-training-app
            port:
              number: 80
      - path: /acc/api/(.*)
        pathType: Prefix
        backend:
          service:
            name: back-training-app
            port:
              number: 80
