kind: Deployment
apiVersion: apps/v1
metadata:
  name: back-training-app
  namespace: form-k8s-{{ .Values.global.env }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: back-training-app
  template:
    metadata:
      labels:
        app: back-training-app
    spec:
      containers:
      - name: back-training-app
        image: "{{ .Values.global.repoUrl }}/{{ .Values.image }}:{{ .Values.tag }}"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          failureThreshold: 2
          periodSeconds: 5
        resources:
          requests:            
            memory: "536M"
          limits:
            memory: "536M"
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: MONGO_USERNAME        
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: MONGO_PASSWORD  
        - name: MONGO_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: back-configmap
              key: MONGO_HOSTNAME
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: back-configmap
              key: MONGO_PORT
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: back-configmap
              key: MONGO_DB
