kind: Deployment
apiVersion: apps/v1
metadata:
  name: front-training-app
  namespace: form-k8s-{{ .Values.env }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: front-training-app
  template:
    metadata:
      labels:
        app: front-training-app
    spec:
      containers:
      - name: front-training-app
        image: {{ .Values.repoUrl }}/{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
        imagePullPolicy: Always
        env:
        - name: env
          value: {{ .Values.env }}
          
